apiVersion: v1
data:
  clientSecret: NzhjZjVjZjAtOTFkZi0xMWVkLWExZWItMDI0MmFjMTIwMDAy
kind: Secret
metadata:
  name: openid-client-secret
  namespace: openshift-authentication
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
